config/routes.rb
Rails.application.routes.draw do

  mount WalletoneMiddleware.new => '/w1_callback'

  root 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  post '/tinymce_assets' => 'tinymce_assets#create'

  get '/how_it_works' => 'static#how_it_works', as: :how_it_works
  get '/pricing' => 'static#pricing', as: :pricing
  get '/questions' => 'static#questions', as: :questions
  match '/send_question' => 'static#send_question', as: :send_question, via: [:get, :post]
  get '/privacy_policy' => 'static#privacy_policy', as: :privacy_policy
  get '/terms_of_use' => 'static#terms_of_use', as: :terms_of_use

  resources :categories, only: [:show]
  resources :users do
    get :withdraws, on: :collection
  end
  resources :custom_questions
  resources :withdraws

  namespace :blog do
    resources :articles, only: [:index, :show] do
      resources :likes, only: [:create], on: :member
      resources :comments, only: [:create, :index], on: :member
    end
  end

  resources :campaigns do
    member do
      resources :donations do
        get :load_more, on: :collection
      end
    end
    resources :likes, only: [:create], on: :member
    resources :comments, only: [:create, :index], on: :member
  end
  resources :comments do
    resources :likes, on: :member
  end

  namespace :dashboard do
    match 'campaigns/:campaign_id/select_picture' => 'campaigns#select_picture', as: :select_campaign_picture, via: [:post, :patch]
    match 'campaigns/:campaign_id/select_video' => 'campaigns#select_video', as: :select_campaign_video, via: [:post, :patch]

    resources :notifications, only: :index
    resources :comments, only: :index
    resources :donations, only: :index

    resources :campaigns, param: :campaign_id do

      patch :crop, on: :member
      post :activate, on: :member
      post :post_update, on: :member

      resources :rewards

      member do
        resources :campaign_steps, path: :steps

        get :next_step, :prev_step
      end
    end
    resources :users, only: :show do
      get :vk_photos, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: :show do
        get :vk_photos, on: :member
      end


      get 'cities/search' => 'cities#search', as: :search_cities
    end
  end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  post '/donations/check' => 'donations#check', as: :check_payment

end

app/views/shared/_adsense_left.html.haml
.ad-sense
	.ad-wrapper
		%p AdSense
		%p
			%small 160x600

app/views/shared/_categories.html.haml
%h5 Популярные категории
= render Category.popular

%h5 Все категории
= render Category.regular

app/views/shared/_donation.html.haml
%li
	.avatar-part
		= render_user_avatar_for donation.user, image_styles: 'w50 img-circle'
	.info-part
		- if donation.user.present?
			= raw "#{link_to donation.author.name, donation.author} внес пожертвование для Вашей кампании '#{link_to donation.campaign.title, donation.campaign}'"
		- else
			= raw "Неизвестный пользователь внес пожертвование для Вашей кампании '#{link_to donation.campaign.title, donation.campaign}'"
		%span.time= donation.created_at.strftime("%d.%m.%Y %H:%M")
	.money-part
		= "#{construct_amount(donation.amount, donation.currency)}".html_safe

app/views/shared/_footer.html.haml
%footer
	.container
		.row
			.col-md-2
				%h5 Знакомство
				%ul
					%li= link_to 'Как это работает?', '/how_it_works'
					%li= link_to 'Онлайн блог', '/blog/articles'
					%li= link_to 'Вопросы и ответы', '/questions'
					%li= link_to 'Задать вопрос', send_question_path
			.col-md-2
				%h5 О нас
				%ul
					%li= link_to 'Смотреть видео', '#'
					%li= link_to 'Отзывы', '#'
					%li= link_to 'Цены и тарифы', '/pricing'
					%li= link_to 'Правила и условия', '/how_it_works'
			.col-md-2
				%h5 Связаться с нами
				%ul
					%li= link_to 'Задать вопрос', send_question_path
					%li= link_to 'Часто задаваемые вопросы', '/questions'
					%li= link_to 'Центр помощи', '/questions'
			.col-md-3
				%h5 Популярные
				%ul
					- Campaign.popular.first(4).each do |c|
						%li= link_to c.title, c
			.col-md-3.text-right
				= link_to '/questions' do
					= image_tag 'guarantee.png'
				%p Для связи с нами:
				%p Тех. поддержка - support@myfundraise.ru
				%p Администрация - admin@myfundraise.ru


		#supported-currencies
			= image_tag 'flag_ua.png'
			= image_tag 'flag_ru.png'
			%span Поддерживаемые валюты

			= render 'shared/social_counters'


		%ul.footer-menu
			%li= link_to "Блог", '/blog/articles'
			%li= link_to "Условия пользования", terms_of_use_path
			%li= link_to "Политика конфидециальности", privacy_policy_path
			%li= "&copy; #{Date.today.year} MyFundraise".html_safe

app/views/shared/_modals.html.haml
= render_modal id: 'sign_up'
= render_modal id: 'sign_in'

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        = image_tag 'logo.png', size: "156x50", class: "gutter-top-5"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if campaign_page?
          - if user_signed_in?
            %li= link_to "Начать свой сбор", new_dashboard_campaign_path, class: 'btn btn-lg'
          - else
            %li= link_to "Начать свой сбор", '#', class: "btn btn-lg", data: { toggle: "modal", target: "#sign_up" }
        - else
          %li= link_to "Смотреть видео", '#'


      %ul.nav.navbar-nav.navbar-right
        = render partial: 'menu_items/menu_item', collection: MenuItem.enabled

        - if user_signed_in?
          %li.dropdown
            = link_to '#', class: "dropdown-toggle", data: { toggle: "dropdown" }, role: "button", aria: { haspopup: true, expanded: false } do
              = render_user_avatar_for current_user, image_styles: "navbar-avatar", fake_styles: "small pull-left gutter-right-5"
              = current_user.name || current_user.email
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to current_user do
                  = fa_icon :"user"
                  Моя страница
                = link_to withdraws_users_path do
                  = fa_icon :"credit-card-alt"
                  Вывод средств

              %li.divider(role="separator")
              %li
                = link_to dashboard_notifications_path do
                  %span.pull-right= current_user.activities.where(is_seen: false).count
                  = fa_icon :"bell"
                  Все уведомления
              %li
                = link_to dashboard_notifications_path(tab: :donation) do
                  %span.pull-right= current_user.campaigns.sum(:donations_count)
                  = fa_icon :"usd"
                  Пожертвования
              %li
                = link_to dashboard_notifications_path(tab: :comment) do
                  %span.pull-right= current_user.campaigns.sum(:comments_count)
                  = fa_icon :"comment"
                  Комментарии
              %li.divider(role="separator")
              %li
                = link_to new_dashboard_campaign_path do
                  = fa_icon :"plus-square"
                  Новая компания

              %li.divider(role="separator")
              %li
                = link_to destroy_user_session_path, method: :delete do
                  = fa_icon :"power-off"
                  Выход
        - else
          - unless campaign_page?
            %li= link_to 'Зарегистрироваться', '#', class: "reg-link", data: { toggle: "modal", target: "#sign_up" }
            %li= link_to 'Войти', '#', data: { toggle: "modal", target: "#sign_in" }

app/views/shared/_notifications.html.haml
- notifications.each do |notification|
	%li= render_notification notification

app/views/shared/_partners.html.haml
#partners-wrapper
	.container
		#partners-flex.text-center= render Partner.all

app/views/shared/_promo.html.haml
.promo-bg
	.container
		.row
			.col-md-10.col-md-offset-1
				.row
					.col-md-12
						= image_tag 'logo.png', size: "312x100", class: "gutter-top-5"
						.non-semantic-protector
							%h3.ribbon
								%strong.ribbon-content WORLD'S #1 FUNDRAISING SITE
					.col-md-6.text-left
						= fa_icon :check
						Создание страницы для сбора за пару минут
					.col-md-6.text-left
						= fa_icon :check
						Интеграция в соц. сети: VK, Одноклассники
					.col-md-6.text-left
						= fa_icon :check
						Более 50 способов оплаты
					.col-md-6.text-left
						= fa_icon :check
						Быстрый вывод собранных средств
					.col-md-6.text-left
						= fa_icon :check
						Никаких ограничительных сроков
					.col-md-6.text-left
						= fa_icon :check
						Быстрая техническая поддержка
					.col-md-12
						= link_to "Создать компанию", new_dashboard_campaign_path, class: 'btn btn-lg'

app/views/shared/_social_counters.html.erb
<div class="pull-right" style="margin-right: 10px;">
  <!-- Put this script tag to the <head> of your page -->
  <script type="text/javascript" src="https://vk.com/js/api/share.js?94" charset="windows-1251"></script>

  <!-- Put this script tag to the place, where the Share button will be -->
  <script type="text/javascript"><!--
  document.write(VK.Share.button(false,{type: "round", text: "Рассказать друзьям"}));
  --></script>
</div>

<div class="pull-right" style="margin-right: 10px;">
  <div id="ok_shareWidget"></div>
  <script>
  !function (d, id, did, st, title, description, image) {
    var js = d.createElement("script");
    js.src = "https://connect.ok.ru/connect.js";
    js.onload = js.onreadystatechange = function () {
    if (!this.readyState || this.readyState == "loaded" || this.readyState == "complete") {
      if (!this.executed) {
        this.executed = true;
        setTimeout(function () {
          OK.CONNECT.insertShareWidget(id,did,st, title, description, image);
        }, 0);
      }
    }};
    d.documentElement.appendChild(js);
  }(document,"ok_shareWidget",document.URL,'{"sz":20,"st":"straight","ck":2}',"","","");
  </script>
</div>


<div class="pull-right" style="margin-right: 10px;">
  <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>