config/routes.rb
Rails.application.routes.draw do

  mount WalletoneMiddleware.new => '/w1_callback'

  root 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  post '/tinymce_assets' => 'tinymce_assets#create'

  get '/how_it_works' => 'static#how_it_works', as: :how_it_works
  get '/pricing' => 'static#pricing', as: :pricing
  get '/questions' => 'static#questions', as: :questions
  match '/send_question' => 'static#send_question', as: :send_question, via: [:get, :post]
  get '/privacy_policy' => 'static#privacy_policy', as: :privacy_policy
  get '/terms_of_use' => 'static#terms_of_use', as: :terms_of_use

  resources :categories, only: [:show]
  resources :users do
    get :withdraws, on: :collection
  end
  resources :custom_questions
  resources :withdraws

  namespace :blog do
    resources :articles, only: [:index, :show] do
      resources :likes, only: [:create], on: :member
      resources :comments, only: [:create, :index], on: :member
    end
  end

  resources :campaigns do
    member do
      resources :donations do
        get :load_more, on: :collection
      end
    end
    resources :likes, only: [:create], on: :member
    resources :comments, only: [:create, :index], on: :member
  end
  resources :comments do
    resources :likes, on: :member
  end

  namespace :dashboard do
    match 'campaigns/:campaign_id/select_picture' => 'campaigns#select_picture', as: :select_campaign_picture, via: [:post, :patch]
    match 'campaigns/:campaign_id/select_video' => 'campaigns#select_video', as: :select_campaign_video, via: [:post, :patch]

    resources :notifications, only: :index
    resources :comments, only: :index
    resources :donations, only: :index

    resources :campaigns, param: :campaign_id do

      patch :crop, on: :member
      post :activate, on: :member
      post :post_update, on: :member

      resources :rewards

      member do
        resources :campaign_steps, path: :steps

        get :next_step, :prev_step
      end
    end
    resources :users, only: :show do
      get :vk_photos, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: :show do
        get :vk_photos, on: :member
      end


      get 'cities/search' => 'cities#search', as: :search_cities
    end
  end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  post '/donations/check' => 'donations#check', as: :check_payment

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  paginates_per 10
  include AASM

  include ::PublicActivity::Model

  belongs_to :user
  belongs_to :campaign
  belongs_to :currency

  has_many :payments, dependent: :destroy

  validates_presence_of :campaign, :currency, :amount

  after_initialize :generate_secret_key!
  after_destroy :decrement_counters

  aasm do
  	state :pending, initial: true
  	state :paid
  	state :failed

  	event :pay, after: :increment_counters do
  		transitions from: [:pending, :failed], to: :paid, after: :after_pay_callback
  	end

  	event :fail do
  		transitions from: :pending, to: :failed
  	end
  end

  def increment_counters
    total_amount = campaign.total_amount + self.amount
    campaign.update total_amount: total_amount,
                    percentage: (total_amount.to_f / campaign.goal * 100),
                    donations_count: (campaign.donations_count + 1)
  end

  def decrement_counters
    return unless paid?
    total_amount = campaign.total_amount - self.amount
    campaign.update total_amount: total_amount,
                    percentage: (total_amount.to_f / campaign.goal * 100),
                    donations_count: (campaign.donations_count - 1)
  end

  def author
    user || User.anonym
  end

  def after_pay_callback
    create_activity action: "create", recipient: campaign.user, owner: user
    campaign.update to_withdraw: (campaign.to_withdraw + self.amount * 0.93)
  end

private

  def generate_secret_key!
  	self.secret_key = Digest::MD5.hexdigest(Faker::Crypto.md5 + Time.now.to_i.to_s) unless secret_key
  end

end

app/controllers/dashboard/donations_controller.rb
class Dashboard::DonationsController < ApplicationController

	PAGE_SIZE = 20
	
	def index
		@donations = Donation.where(campaign_id: current_user.campaigns.pluck(:id))
												 .order(created_at: :desc)
												 .page(params[:page]).per PAGE_SIZE
	end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

	W1_SECRET_KEY = Rails.application.secrets.w1_secret_key

	before_action :fetch_campaign, except: [:check, :test]

	def create
		@donation = Donation.new permitted_params.merge(default_params)

		if @donation.save
			run_payment_flow
		else
			render :new
		end
	end

	def new
		@donation = Donation.new amount: params[:amount]
	end

	def check
		p params
		Myfundraise::Payments::Interkassa::InteractorCallback.new(params: params).run!
		render text: ""
	end

	def load_more
		@donations = @campaign.donations.page params[:page]
	end

private

	def fetch_campaign
		@campaign = Campaign.find params[:id]
	end

	def permitted_params
		params.require(:donation).permit :amount, :message, :anonymous, :name, :email
	end

	def default_params
		{ user_id: current_user.try(:id), campaign_id: @campaign.id, currency_id: @campaign.currency.id }
	end

	def run_payment_flow
		# payment = Walletone::Payment.new(
		# 	WMI_MERCHANT_ID:    Rails.application.secrets.w1_merchant_id,
		# 	WMI_PAYMENT_AMOUNT:  @donation.amount,
		# 	WMI_CURRENCY_ID:     @donation.currency.wallet_one_id,
		# 	WMI_SUCCESS_URL: root_url,
		# 	DONATION_SECRET_KEY: @donation.secret_key
		# )
		# payment.sign! W1_SECRET_KEY

		# render locals: { form: payment.form }
	end

end

app/views/donations/_donation.html.haml
.donation
	.donation-image
		- donor = can?(:show, donation) ? donation.author : User.anonym
		= render_user_avatar_for donor, image_styles: "img-circle"
	.donation-info
		.info
			%b= "#{construct_amount(donation.amount, donation.currency)}".html_safe
			от
			- if can?(:show, donation)
				= link_to "#{donation.name}", '#'
			- else
				%u Анонима

		.time= donation.created_at.strftime "%d.%m.%Y %H:%M"
	- if can?(:show, donation)
		%p= donation.message

app/views/donations/create.html.haml
/ .text-center.campaign-block.alone
/ 	= image_tag "receipt.png", size: "128x128", class: "gutter-top-20 gutter-bottom-20"

/ 	%h5.gutter-bottom-30 В течение 5-и секунд вы будете переправлены на страницу оплаты.
/ 	= form_tag form.checkout_url, form.options.merge(data: { autosubmit: true }) do |f|
/ 		= raw form.hidden_fields_tags
/ 		= button_tag 'Перейти к оплате', class: 'btn btn-bordered gutter-bottom-15', data: { disable_with: 'Переправляю на сайт оплаты..' }

/ %p.sub-campaign-block Продолжая, вы согласны с условиями пользования MyFundraise и политикой конфиденциальности.



.text-center.campaign-block.alone
	= image_tag "receipt.png", size: "128x128", class: "gutter-top-20 gutter-bottom-20"

	%h5.gutter-bottom-30 В течение 5-и секунд вы будете переправлены на страницу оплаты.
	= form_tag "https://sci.interkassa.com/", data: { autosubmit: true } do |f|
		= hidden_field_tag :"ik_co_id", "57fb5c383b1eafee6e8b4569"
		= hidden_field_tag :"ik_pm_no", @donation.secret_key
		= hidden_field_tag :"ik_am", @donation.amount
		= hidden_field_tag :"ik_cur", @donation.currency.code
		= hidden_field_tag :"ik_desc", "Пожертвование #{@donation.amount}#{@donation.currency.code} на '#{@donation.campaign.title}'"
		= hidden_field_tag :"ik_x_message", @donation.message
		= hidden_field_tag :"ik_suc_u", campaign_url(@donation.campaign)
		= hidden_field_tag :"ik_suc_m", "GET"
		= hidden_field_tag :"ik_fal_u", campaign_url(@donation.campaign)
		= hidden_field_tag :"ik_fal_m", "GET"
		= hidden_field_tag :"ik_pnd_u", campaign_url(@donation.campaign)
		= hidden_field_tag :"ik_pnd_m", "GET"

		= button_tag 'Перейти к оплате', class: 'btn btn-bordered gutter-bottom-15', data: { disable_with: 'Переправляю на сайт оплаты..' }

%p.sub-campaign-block Продолжая, вы согласны с условиями пользования MyFundraise и политикой конфиденциальности.

app/views/donations/load_more.js.erb
$("#donations-list").append("<%= j render @donations %>");
$(".donations-list-more-link").html("<%= j link_to_next_page @donations, 'Показать еще', remote: true, params: { controller: :donations, action: :load_more } %>")

app/views/donations/new.html.haml
.fake-page
	.donation-campaign-info
		= image_tag @campaign.picture.url(:medium), size: "300x200"

		%span Название кампании
		%h5= @campaign.title

		%span Автор кампании
		%h5= @campaign.user.name

		%span Адрес
		%h5= @campaign.address

		%span Дата публикации
		%h5= @campaign.created_at.strftime "%d.%m.%Y %H:%M"

	.donation-form
		= form_for @donation do |f|
			%label Сумма пожертвования
			.amount-form
				%span= @campaign.currency.sign.html_safe
				= f.text_field :amount, id: "amount", autofocus: true, placeholder: "1000"

			- if @donation.errors[:amount].any?
				.field-error.text-danger.gutter-top--15.gutter-bottom-20 необходимо ввести сумму пожертвования

			.helper= raw "Перед отправкой пожертвования, пожалуйста, проверьте правильность своих персональных данных! Редактировать их можно в #{link_to 'личном кабинете', '#'}"

			.helper
				Использовать мой профиль:
				= link_to user_vkontakte_omniauth_authorize_path(return_url: new_donation_path(@campaign)), style: "font-size: 20px" do
					= fa_icon :vk
				или
				= link_to user_odnoklassniki_omniauth_authorize_path(return_url: new_donation_path(@campaign)), style: "font-size: 20px" do
					= fa_icon :odnoklassniki

			%label Ваше имя
			= f.text_field :name, value: current_user.try(:name), class: "stylized"

			%label Ваш Email
			= f.text_field :email, value: current_user.try(:email), class: "stylized"

			%label Сообщение
			= f.text_area :message

			%label.checkbox
				= f.check_box :anonymous, data: { skin: "square", color: "green" }, class: "icheck-me"
				Показывать текст и моё имя только получателю

			.gutter-top-30
				= submit_tag "Перейти к оплате", class: "btn btn-lg myf-btn myf-btn-primary gutter-right-10"
				= link_to "Вернуться назад", campaign_path(@campaign), class: "btn btn-link pull-right", style: "padding-right:0;"
			.helper.gutter-top-15.gutter-bottom-0= raw "Внимание! После оплаты не спешите уходить, Вам будет предложено сделать репост с благодарностью."