config/routes.rb
Rails.application.routes.draw do

  mount WalletoneMiddleware.new => '/w1_callback'

  root 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  post '/tinymce_assets' => 'tinymce_assets#create'

  get '/how_it_works' => 'static#how_it_works', as: :how_it_works
  get '/pricing' => 'static#pricing', as: :pricing
  get '/questions' => 'static#questions', as: :questions
  match '/send_question' => 'static#send_question', as: :send_question, via: [:get, :post]
  get '/privacy_policy' => 'static#privacy_policy', as: :privacy_policy
  get '/terms_of_use' => 'static#terms_of_use', as: :terms_of_use

  resources :categories, only: [:show]
  resources :users do
    get :withdraws, on: :collection
  end
  resources :custom_questions
  resources :withdraws

  namespace :blog do
    resources :articles, only: [:index, :show] do
      resources :likes, only: [:create], on: :member
      resources :comments, only: [:create, :index], on: :member
    end
  end

  resources :campaigns do
    member do
      resources :donations do
        get :load_more, on: :collection
      end
    end
    resources :likes, only: [:create], on: :member
    resources :comments, only: [:create, :index], on: :member
  end
  resources :comments do
    resources :likes, on: :member
  end

  namespace :dashboard do
    match 'campaigns/:campaign_id/select_picture' => 'campaigns#select_picture', as: :select_campaign_picture, via: [:post, :patch]
    match 'campaigns/:campaign_id/select_video' => 'campaigns#select_video', as: :select_campaign_video, via: [:post, :patch]

    resources :notifications, only: :index
    resources :comments, only: :index
    resources :donations, only: :index

    resources :campaigns, param: :campaign_id do

      patch :crop, on: :member
      post :activate, on: :member
      post :post_update, on: :member

      resources :rewards

      member do
        resources :campaign_steps, path: :steps

        get :next_step, :prev_step
      end
    end
    resources :users, only: :show do
      get :vk_photos, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: :show do
        get :vk_photos, on: :member
      end


      get 'cities/search' => 'cities#search', as: :search_cities
    end
  end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  post '/donations/check' => 'donations#check', as: :check_payment

end

app/controllers/dashboard/campaign_steps_controller.rb
class Dashboard::CampaignStepsController < ApplicationController
	include Wicked::Wizard

	before_action :fetch_campaign

	prepend_before_action :set_steps

	def show
		@campaign.update_attribute :step, params[:id]
		@rewards = @campaign.rewards
		redirect_to @campaign and return if @campaign.step == 'activate' && !@campaign.is_draft?
		render_wizard
	end

	def update
	  @campaign.attributes = permitted_params
	  render_wizard @campaign
	end

private

	def set_steps
		self.steps = Campaign::STEPS
	end

	def permitted_params
		params.require(:campaign).permit!
	end

	def fetch_campaign
		@show_promo = false
		@campaign = Campaign.find params[:campaign_id]
	end

end

app/controllers/dashboard/campaigns_controller.rb
class Dashboard::CampaignsController < ApplicationController

	before_action :load_campaign, only: [:show, :select_picture, :select_video, :prev_step, :next_step, :crop, :activate, :edit, :update, :destroy, :post_update]

	def new
		@show_promo = false
		@campaign = Campaign.new
	end

  def create
  	@show_promo = false
  	@campaign = current_user.campaigns.new permitted_params
	  if @campaign.save
	    redirect_to dashboard_campaign_steps_path(@campaign, id: :media)
	  else
	    render :new
	  end
  end

  def show
  	redirect_to dashboard_campaign_steps_path(@campaign)
  end

	def select_picture
		if params[:type] == "regular"
			@campaign.update params.require(:campaign).permit(:picture)
		else
			@campaign.update remote_picture_url: params[:url]
		end

		if @campaign.picture.present?
			@campaign.next_step!
			redirect_to dashboard_campaign_steps_path(campaign_id: @campaign.id, id: @campaign.current_step)
		else
			redirect_to dashboard_campaign_steps_path(campaign_id: @campaign.id, id: "media")
		end
	end

	def select_video
		@campaign.update params.require(:campaign).permit(:video_url)
		if @campaign.video_url.present?
			@campaign.next_step!
			redirect_to dashboard_campaign_steps_path(campaign_id: @campaign.id, id: @campaign.current_step)
		else
			redirect_to dashboard_campaign_steps_path(campaign_id: @campaign.id, id: "media")
		end
	end

	def next_step
		@campaign.next_step!
		redirect_to dashboard_campaign_steps_path(campaign_id: @campaign.id, id: @campaign.current_step)
	end

	def prev_step
		@campaign.prev_step!
		redirect_to dashboard_campaign_steps_path(campaign_id: @campaign.id, id: @campaign.current_step)
	end

	def crop
		@campaign.update permitted_params
		redirect_to dashboard_campaign_steps_path(campaign_id: @campaign.id, id: "media_confirm")
	end

	def activate
		@campaign.update is_draft: false
		@campaign.next_step!
		redirect_to @campaign
	end

	def edit
	end

	def update

	end

	def destroy
		@campaign.destroy
		redirect_to root_path
	end

	def post_update
		@update = @campaign.updates.create params.require(:update).permit!
	end

private

	def permitted_params
		params.require(:campaign).permit!
	end

	def load_campaign
		@campaign = Campaign.find params[:campaign_id]
	end

end

app/controllers/dashboard/comments_controller.rb
class Dashboard::CommentsController < ApplicationController

	PAGE_SIZE = 20
	
	def index
		@notifications = PublicActivity::Activity.where(recipient_id: current_user.id, recipient_type: "User")
																						 .order(created_at: :desc)
																						 .page(params[:page]).per PAGE_SIZE
	end

end

app/controllers/dashboard/donations_controller.rb
class Dashboard::DonationsController < ApplicationController

	PAGE_SIZE = 20
	
	def index
		@donations = Donation.where(campaign_id: current_user.campaigns.pluck(:id))
												 .order(created_at: :desc)
												 .page(params[:page]).per PAGE_SIZE
	end

end

app/controllers/dashboard/notifications_controller.rb
class Dashboard::NotificationsController < ApplicationController

	PAGE_SIZE = 20

	POSSIBLE_TABS = %w(all donation comment like)

	def index
		@tab = current_tab
		scope = PublicActivity::Activity.where(recipient_id: current_user.id, recipient_type: "User")
		scope = scope.where "key ILIKE ?", "#{@tab}.%" if @tab != POSSIBLE_TABS.first

		@notifications = scope.order(created_at: :desc).page(params[:page]).per PAGE_SIZE
	end

private

	def current_tab
		POSSIBLE_TABS.include?(params[:tab]) ? params[:tab] : POSSIBLE_TABS.first
	end

end

app/controllers/dashboard/rewards_controller.rb
class Dashboard::RewardsController < ApplicationController

  before_action :find_campaign

  def new
    @reward = @campaign.rewards.new
  end

  def create
    @campaign.rewards.create reward_params
    render 'reload'
  end

  def destroy
    @reward = Reward.find(params[:id]).destroy
    render 'reload'
  end

  private

  def find_campaign
    @campaign = Campaign.find params[:campaign_campaign_id]
  end

  def reward_params
    params.require(:reward).permit!
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
	
	def vk_photos
		use_case = ::Myfundraise::Profile::SocialPhotos::Vkontakte.new user_id: params[:id], count: params[:count], offset: params[:offset]
		@photos = use_case.fetch
	end

end

app/views/dashboard/campaign_steps/activate.html.haml
.new-campaign-block
	= form_for @campaign, url: dashboard_campaign_step_path(campaign_id: @campaign.id) do |f|
		.campaign-container
			%h3 Компания готова к публикации
			
			.grayed.text-center
				= image_tag @campaign.picture.url(:medium), size: "300x200"
				.sample-campaign
					%h2= @campaign.title
					%p= campaign_url(@campaign)


			.actions.text-center
				= link_to "Назад".html_safe, dashboard_campaign_steps_path(@campaign, id: @campaign.prev_step), class: "pull-left"
				= link_to 'Опубликовать', activate_dashboard_campaign_path(@campaign), class: "pull-right green-btn", method: :post

app/views/dashboard/campaign_steps/description.html.haml
.new-campaign-block
  = form_for @campaign, url: dashboard_campaign_step_path(campaign_id: @campaign.id) do |f|
    .campaign-container
      %h3 Расскажите свою историю

      .grayed.form-group
        = f.text_area :description, class: "form-control editor", placeholder: "Введите сюда вашу историю. Очень важно чтобы рассказ был честный, интересный и главное правдивый. Люди хотят знать всю конкретику и подробности. Напишите все о ваших потребностях и нуждах. ", rows: 10

        .gutter-top-20
          = raw "Дополнительные возможности: #{link_to 'Предложить награду', new_dashboard_campaign_reward_path(@campaign), remote: true} (при пожертвовании человек получит от Вас награду):"

          #rewards-list
            = render partial: 'dashboard/rewards/reward', collection: @campaign.rewards, as: :reward

    .actions.text-center
      = link_to "Предыдущий шаг".html_safe, prev_step_dashboard_campaign_path(@campaign), class: "pull-left"
      = f.submit "Подтвердить".html_safe, class: "pull-right green-btn"

.modal-container

app/views/dashboard/campaign_steps/general.html.haml
.new-campaign-block
	= form_for @campaign, url: dashboard_campaign_step_path(campaign_id: @campaign.id), html: { class: 'myfundraise-form' } do |f|
		= f.hidden_field :currency_id

		%h4= "Привет, #{current_user.try(:first_name)}, введите Ваши цели:"
		.goal
			%span.currency-selector
				%span(onclick="CurrencySelector.toggle()")= @campaign.currency.sign.html_safe
				%ul.selector
					- Currency.all.each do |c|
						%li(onclick="CurrencySelector.select(#{c.to_json})")= "#{c.sign} #{c.name}".html_safe

			= text_field_tag :"campaign[goal]", @campaign.goal, placeholder: "0"
		- if @campaign.errors[:goal].any?
			.gutter-top--15.gutter-bottom-20.field-error.text-danger= @campaign.errors[:goal].first

		.form-group
			= f.label :title
			= f.text_field :title, class: "form-control input-lg", placeholder: "Например: Волонтерская помощь на лечение Вики Шевченко"
			.field-error.text-danger= @campaign.errors[:title].first
		.form-group
			= f.label :city_id
			= f.select :city_id, {}, {include_blank: false}, id: "select-city", data: { placeholder: "Выберите город из списка" }, class: 'form-control input-lg'
			.field-error.text-danger= @campaign.errors[:city].first
		.form-group
			= f.label :category_id
			= f.select :category_id, Category.all.collect {|c| [c.title, c.id] }, { include_blank: false }, class: "form-control input-lg", placeholder: "Enter your ZIP or Postal Code..."
			.field-error.text-danger= @campaign.errors[:category].first
		.form-group.text-center.gutter-top-30
			= f.submit "Дальше", class: "btn btn-myf btn-lg"

		.helper Не переживайте, Вы сможете вносить изменения в кампанию в любой момент.

app/views/dashboard/campaign_steps/instagram.html.haml
.new-campaign-block
  .campaign-container
    %h3 Добавить профиль Instagram

    .grayed.form-group
      = link_to "Добавить Instagram", user_instagram_omniauth_authorize_path(return_url: dashboard_campaign_steps_url(@campaign, id: @campaign.next_step))

  .actions.text-center
    = link_to "Предыдущий шаг".html_safe, prev_step_dashboard_campaign_path(@campaign), class: "pull-left"
    = link_to "Пропустить".html_safe, dashboard_campaign_steps_path(@campaign, id: @campaign.next_step), class: "pull-right green-btn"

app/views/dashboard/campaign_steps/media.html.haml
.new-campaign-block
	.campaign-container
		.select-container
			%h3 Добавить фото или видео
			.photos-container.grayed.row
				%div
					= link_to vk_photos_dashboard_user_path(current_user, count: 9, campaign_id: @campaign.id), remote: true, class: "select-block" do
						= fa_icon :vk
						Выбрать из ВКонтакте
				%div
					= form_for @campaign, url: dashboard_select_campaign_picture_path(@campaign, type: "regular"), html: { class: "hidden" } do |f|
						= f.file_field :picture
						= f.submit

					= link_to '#', class: "select-block", onclick: "selectCoverFromComputer()" do
						= fa_icon :paperclip
						Загрузить фото
				%div
					= link_to 'javascript:void(0)', class: "select-block", onclick: "return MediaSelector.showVideo();" do
						= fa_icon :youtube
						YouTube или Vimeo

			.actions.text-center
				= link_to "Назад".html_safe, dashboard_campaign_steps_path(@campaign, id: @campaign.prev_step), class: "pull-left"
				= link_to "Пропустить".html_safe, dashboard_campaign_steps_path(@campaign, id: 'description'), class: "pull-right"
		.video-container.hidden
			= form_for @campaign, url: dashboard_select_campaign_video_path(@campaign), html: { class: "myfundraise-form" } do |f|
				%h3
					Enter the video URL
					= link_to "Назад", 'javascript:void(0);', class: "pull-right", onclick: "return MediaSelector.showAllVariants();"
				.form
					.form-group
						= f.text_field :video_url, placeholder: "Place the YouTube or Vimeo URL...", class: "form-control input-lg"

				.actions.text-center
					= link_to "Назад".html_safe, dashboard_campaign_steps_path(@campaign, id: @campaign.prev_step), class: "pull-left"
					= f.submit "Далее", class: "pull-right green-btn"

app/views/dashboard/campaign_steps/media_confirm.html.haml
.new-campaign-block
	.campaign-container
		%h3 Подтверждение обложки

		.grayed
			= image_tag @campaign.picture.url(:medium), class: "img-responsive"

		.actions.text-center
			= link_to "Назад".html_safe, prev_step_dashboard_campaign_path(@campaign), class: "pull-left"
			= link_to "Подтвердить".html_safe, next_step_dashboard_campaign_path(@campaign), class: "pull-right green-btn"

app/views/dashboard/campaign_steps/media_crop.html.haml
= form_for @campaign, url: crop_dashboard_campaign_path(@campaign) do |f|
	- %w[x y w h].each do |attribute|
		= f.hidden_field "crop_#{attribute}"

	.new-campaign-block
		.campaign-container
			%h3 Обрезка обложки
			.grayed
				= image_tag @campaign.picture.url(:original), id: "cropbox", class: "img-responsive", data: { width: @campaign.width, height: @campaign.height }
			.actions.text-center
				= link_to "Изменить обложку".html_safe, prev_step_dashboard_campaign_path(@campaign), class: "pull-left"
				= f.submit "Подтвердить", class: "pull-right green-btn"

app/views/dashboard/campaign_steps/new.html.haml
= form_for @campaign do |f|
  = f.error_messages
  = render "#{@order.current_step}_step", f: f
  %p= f.submit "Continue"
  %p= f.submit "Back", :name => "previous_button" unless @order.first_step?

/ %p= link_to "Back to List", orders_path

app/views/dashboard/campaign_steps/share.html.haml
.new-campaign-block
  .campaign-container
    %h3 Поделиться на ВК может увеличить пожертвования 3х

    .grayed.text-center
      = image_tag @campaign.picture.url(:medium), size: "300x200"
      .sample-campaign
        %h2.gutter-top-10= @campaign.title
        %p= campaign_url(@campaign)

      .text-center.gutter-top-40.gutter-bottom-10
        = link_to 'javascript:void(0);', onclick: "Share.vkontakte('#{campaign_url(@campaign)}','#{@campaign.title}','#{asset_url(@campaign.picture.url)}','', '#{dashboard_campaign_steps_path(@campaign, id: 'activate')}');return false;", class: "share-vk" do
          %span.left-part= fa_icon :vk
          Поделиться ВК

  .actions.text-center
    = link_to "Предыдущий шаг".html_safe, prev_step_dashboard_campaign_path(@campaign), class: "pull-left"
    = link_to "Далее".html_safe, dashboard_campaign_steps_path(@campaign, id: @campaign.next_step), class: "pull-right green-btn"

app/views/dashboard/campaign_steps/share_confirm.html.haml
.new-campaign-block
  .campaign-container
    %h3 Знаете ли Вы?

    .grayed.form-group
      %p Обмен в социальных сетях является наиболее эффективным для распространения о Вашем сборе

      %ul
        %li Помогает быстро найти доноров из ваших друзей и знакомых
        %li Быстрое распространение информации
        %li Заинтересованность знакомых и друзей ваших друзей

      .text-center.gutter-top-30.gutter-bottom-10
        = link_to 'javascript:void(0);', onclick: "Share.vkontakte('#{campaign_url(@campaign)}','#{@campaign.title}','#{asset_url(@campaign.picture.url)}','', '#{dashboard_campaign_steps_path(@campaign, id: 'activate')}');return false;", class: "share-vk" do
          %span.left-part= fa_icon :vk
          Поделиться ВК

  .actions.text-center
    = link_to "Предыдущий шаг".html_safe, prev_step_dashboard_campaign_path(@campaign), class: "pull-left"
    = link_to "Далее".html_safe, dashboard_campaign_steps_path(@campaign, id: @campaign.next_step), class: "pull-right green-btn"